# Storm-Quantum Cellular Automaton Model

## Microscopic dynamics (quantum cellular automaton + SE unitary)

#### 1. Environment qubits and geometry
- Associate one bath/environment qubits $E_i$ to each system qubit $S_i$.
- The bath qubits inherit the same geometry as the system. 
- We focus on a 2-colorable 2D lattice, as is reflective of a surface code geometry.

#### 2. Environment initial state
Each bath qubit starts in a classical probabilistic mixture:
$$
\rho_{E_i}(0) = \alpha_i \ket{0}\!\!\bra{0} + \beta_i \ket{1}\!\!\bra{1}.
$$
I.e., no initial coherences in the hidden state.

### 3. Red/Black partition
- Partition bath qubits into two disjoint sets:
$$
E = E_{\mathrm{red}} \cup E_{\mathrm{black}}, \quad E_{\mathrm{red}} \cap E_{\mathrm{black}} = \emptyset.
$$
- For surface codes, we can associate red qubits with data qubits and black qubits with syndrome qubits.

#### 4. Single-site classical stochastic update
Each bath qubit undergoes an independent classical transition governed by:
$$
0 \to 1, \text{with probability $a$,} \\
1 \to 0, \text{with probability $b$.}
$$
This is identical to the classical bath update in the 1D temporal storm model.

#### 5. First QCA layer: red -> black
Apply a commuting set of controlled rotations:
$$
U_\mathrm{red} = \prod_{i\in E_\mathrm{red}} \prod_{j\in N(i)}
\left(
    \ket{0}\!\!\bra{0}_{E_i} \otimes I_{E_j} + \ket{1}\!\!\bra{1}_{E_i} \otimes e^{-i\theta X_{E_j}}
\right).
$$
Here:
- Each red qubit controls rotations on its black neighbours,
- all gates commutes,
- this is a standard quantum cellular automaton step.

#### 6. Second QCA layer: black -> red
Similarly, apply
$$
U_\mathrm{black} = \prod_{j\in E_\mathrm{black}} \prod_{i\in N(j)}
\left(
    \ket{0}\!\!\bra{0}_{E_j} \otimes I_{E_i} + \ket{1}\!\!\bra{1}_{E_j} \otimes e^{-i\theta X_{E_i}}
\right).
$$
This completes the QCA update. The total bath unitary per timestep is $U = U_\mathrm{black}U_\mathrm{red}$.

This process can also potentially (?) be generalised for an $n$-colorable graph with $n$ unitaries/QCA layers.

#### 7. System-environment (SE) unitary
For each bath-system pair ($E_i, S_i$), apply the controlled unitary:
$$
U_{SE} = \sum_{k=0}^1 \ket{k}\!\!\bra{k}_{E_i} \otimes Q_k,
$$
where $Q_k$ is a generally a convex combination of Paulis,
$$
Q_k = \sum_{P} \alpha_{k, P} P,
$$
satisfying $\alpha_P \geq 0$, $\sum_P{\alpha_P} = 1$.

#### 8. Pauli twirl on the system
The system is Pauli twirled, enforcing:
- all system coherences vanish,
- the bath sees an effective computational-basis measurement iff,
The Pauli supports of $Q_0$ and $Q_1$ are disjoint:
$$
\mathrm{If} \ X \in \mathrm{support}(Q_0) \Rightarrow X \notin \mathrm{support}(Q_1), \quad\mathrm{etc.}
$$
This ensures the bath is re-classicalised after each interaction with the system, hence the process can be reduced exactly to the dynamics below.

## Effective classical dynamics (probabilistic cellular automaton/HMM description)

The above microscopic dynamics admits a two-layer HMM description:

#### 1-4. Steps 1-4 the same as above

#### 5. First HMM layer
Black qubits are flipped with probability
$$
p(x_i \to x_i \oplus 1 | k_{\mathrm{red}}) = \sin^2(k_\mathrm{red}\theta),
$$
where $k_\mathrm{red}$ are the number of red neighbours in the $\ket{1}\!\!\bra{1}$ state. The fact that we have non-linear scaling $\sin^2(k\theta)$ emerges due to the coherent accumulation of $\theta$ in the underlying quantum bath. AFAIK, this can't be replicated by classical bath dynamics with local, stochastic update rules.

#### 6. Second HMM layer
Similarly, red qubits are flipped with probability
$$
p(x_i \to x_i \oplus 1 | k_{\mathrm{black}}) = \sin^2(k_\mathrm{black}\theta).
$$

#### 7. Bath-system emission

As above:
$$
U_{SE} = \sum_{k=0}^1 \ket{k}\!\!\bra{k}_{E_i} \otimes Q_k.
$$
In other words, Paulis are probabilistically emitted depending on the system qubit depending on its corresponding bath state.

This whole mapping is non-trivial and relies on our choice of $Q_k$'s and bath-bath unitaries.

## Statistical mechanical analysis

Not actual surface code simulations. Just run storm QCA model on bath lattice.

Distance 3 surface code lattice, noise parameters: $a = 0.001, \ b = 0.5$.


![d3density](../figures/d3qca_densities.png)

![d3autocorr](../figures/d3qca_autocorrelations.png)

![d3binder](../figures/d3qca_binder.png)

Distance 5

![d5density](../figures/d5qca_densities.png)

![d5autocorr](../figures/d5qca_autocorrelations.png)

![d5binder](../figures/d5qca_binder.png)

Distance 7

![d7density](../figures/d7qca_densities.png)

![d7autocorr](../figures/d7qca_autocorrelations.png)

![d7binder](../figures/d7qca_binder.png)

Distance 9

![d9density](../figures/d9qca_densities.png)

![d9autocorr](../figures/d9qca_autocorrelations.png)

![d9binder](../figures/d9qca_binder.png)


## Motivation

- The process tensor + system Pauli twirl provides a unique landscape with coherent, quantum dynamics on the bath interacting with a "classicalising" system operation.
- We have a truly physically derived spatiotemporal noise model. Most other papers have arbitrary models for correlated errors (Fowler's local many-qubit errors, my previous detrimental paper), but here I have explicitly constructed model from the microscopic system-bath dynamics, with locality, causality, and coherence.
- Quantum cellular automaton -> probabilistic cellular automaton via twirling a subsystem of the whole process seems novel and previously unexplored. We don't even need to manually apply a dephasing operation on the environment (which seems arbitrary)! Rather, it emerges naturally from interacting with a twirled system.
- This results in unique PCA update rule, with a non-linear propagation kernel $\sin^2(k\theta)$ arising due to coherent bath effects, that cannot be replicated by analogous, local classical bath dynamics.
- The "quantum-enhanced" PCA exhibits a non-equilibrium phase transition with a single tunable parameter $\theta$.
- We show that this mechanism critically and directly affects QEC performance.
- Our model works for non-trivial geometry. We've constructed a 2D spatiotemporal HMM from a fully quantum model.
- All this, and we can very cheaply simulate it! Allowing us to probe the behaviour of high distance QEC codes under this feature-rich noise model.
- It's a huge conceptual bridge, spanning process tensors, Pauli twirling, QCA, PCA criticality, and QEC robustness.

## Proof of mapping

Reduced bath dynamics

$$
\mathcal{E}[\rho_E] 
= \mathrm{Tr}_S\left[
    \sum_{P\in{\{I, X, Y, Z\}}}(I\otimes P) U_{SE} (I\otimes P) (\rho_E \otimes \rho_S) (I\otimes P) U_{SE}^\dagger (I\otimes P)
\right]
$$

\begin{equation*}
    U_{SE} = \sum_k \ket{k}\!\!\bra{k} \otimes V_k
\end{equation*}

\begin{equation*}
    \begin{split}
    \mathcal{E}[\rho_E] 
    &= \mathrm{Tr}_S\left[\frac{1}{4}
    \sum_P(I\otimes P) U_{SE} (I\otimes P) (\rho_E \otimes \rho_S) (I\otimes P) U_{SE}^\dagger (I\otimes P)\right]\\
    &= \mathrm{Tr}_S\left[\frac{1}{4}
    \sum_P U_{SE} (I\otimes P) (\rho_E \otimes \rho_S) (I\otimes P) U_{SE}^\dagger \right] \\
    &= \mathrm{Tr}_S\left[\frac{1}{4}
    \sum_P (\sum_k \ket{k}\!\!\bra{k} \otimes V_k) (I\otimes P) (\rho_E \otimes \rho_S) (I\otimes P) (\sum_l \ket{l}\!\!\bra{l} \otimes V_l) \right]\\
    &= \sum_{kl} \ket{k}\!\!\bra{k} \rho_E \ket{l}\!\!\bra{l} \cdot \mathrm{Tr}\left[\frac{1}{4}
    \sum_P V_k P \rho_S P V_l \right] \\
    &= \sum_{kl} \ket{k}\!\!\bra{k} \rho_E \ket{l}\!\!\bra{l} \cdot \mathrm{Tr}\left[
    V_k (\frac{1}{4}\sum_P  P \rho_S P) V_l \right] \\ 
    &= \sum_{kl} \ket{k}\!\!\bra{k} \rho_E \ket{l}\!\!\bra{l} \cdot \mathrm{Tr}\left[
    V_k V_l \right] \\ 
    &= \sum_{kl} \ket{k}\!\!\bra{k} \rho_E \ket{l}\!\!\bra{l} \delta_{kl} \\ 
    &= \sum_{k} \ket{k}\!\!\bra{k} \rho_E \ket{k}\!\!\bra{k} 
    \end{split}
\end{equation*}

In [32]:
import numpy as np
import qiskit.quantum_info as qi

In [33]:
I = qi.Pauli('I').to_matrix()
X = qi.Pauli('X').to_matrix()
Y = qi.Pauli('Y').to_matrix()
Z = qi.Pauli('Z').to_matrix()

In [34]:
O = (X + 2*Y) / np.sqrt(5)
qi.Operator(O).is_unitary()

True

In [35]:
np.trace(I @ O)

np.complex128(0j)

In [36]:
np.trace(O @ O) / 2

np.complex128(0.9999999999999999+0j)

In [37]:
Y @ X @ Y

array([[ 0.+0.j, -1.+0.j],
       [-1.+0.j,  0.+0.j]])

In [38]:
X @ (X + Y + Z) @ X

array([[-1.+0.j,  1.+1.j],
       [ 1.-1.j,  1.+0.j]])

In [40]:
P = X + Y + Z
I @ P @ I + X @ P @ X + Y @ P @ Y + Z @ P @ Z

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [42]:
np.trace(Y @ Z)

np.complex128(0j)